openapi: 3.0.0
info:
  title: Student Information API
  description: API for managing student information
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /students:
    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                dob:
                  type: string
                  format: date
              required:
                - name
                - email
                - dob
      responses:
        '200':
          description: Student saved successfully
        '500':
          description: Error saving student